version: "3"
services:
  pitemplog:
    image: pitemplog:latest
    restart: unless-stopped
    volumes:
      - ./build:/usr/local/share/templog
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=mariadb
    depends_on:
      - mariadb
    ports:
      - 8080:80

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
    - /tmp/testing/datadir:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=temperatures
      - MYSQL_USER=temp
      - MYSQL_PASSWORD=temp
      - MYSQL_ROOT_PASSWORD=pitemplog_mariadb_pw_pls_change
