module.exports = function(grunt) {  
  require('load-grunt-config')(grunt);
  grunt.registerTask(
    'dev',
    [
      'clean',
      'copy:src',
      'copy:assetsdist',
      'copy:amchartsdist',
      'copy:jquerydist',
      'copy:bootstrapdist',
      'copy:bootstrapdatepicker',
      'exec:build'
    ]
  );
  grunt.registerTask(
    'default',
    [
      'clean',
      'copy:src',
      'copy:assetsdist',
      'copy:amchartsimg',
      'copy:bootstrapfonts',
      'copy:conf',
      'concat',
      'uglify',
      'cssmin',
      'processhtml'
    ]
  );
  grunt.registerTask(
    'build',
    [
      'default',
      'exec:build'
    ]
  );
  grunt.registerTask(
    'deploy',
    [
      'default',
      'exec:deploy'
    ]
  );
  grunt.registerTask(
    'install',
    [
      'default',
      'exec:install',
      'exec:setup'
    ]
  );
  grunt.registerTask(
    'updateimage',
    [
      'default',
      'exec:prepimage',
      'exec:install',
      'exec:updateimage',
      'exec:closeimage'
    ]
  );
  grunt.registerTask('uninstall', ['exec:uninstall']);
};
