#!/bin/sh
### BEGIN INIT INFO
# Provides:          setup_templog_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Setup templog on first boot.
# Description:
### END INIT INFO

. /lib/lsb/init-functions

# shellcheck source=env
[ -f /etc/default/pitemplog ] && . /etc/default/pitemplog

if [ -z "$PITEMPLOG_DIR" ] ;  then
  echo "PITEMPLOG_DIR is not set, please set it in /etc/default/pitemplog" >&2
  exit 1
fi

case "$1" in
  start)
    log_daemon_msg "Starting setup_templog_once" &&
    "$PITEMPLOG_DIR"/_bin/install.sh &&
    update-rc.d setup_templog_once remove &&
    rm /etc/init.d/setup_templog_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
