#!/bin/sh
### BEGIN INIT INFO
# Provides:          setup_templog_db_once
# Required-Start: mysqld
# Required-Stop:
# Should-Start:
# Default-Start: 3
# Default-Stop:
# Short-Description: Setup templog database on first boot.
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting setup_templog_once" &&
    mysql < /usr/local/share/templog/_bin/create_database.sql &&
    update-rc.d setup_templog_db_once remove &&
    rm /etc/init.d/setup_templog_db_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
