# Site settings
title: Raspi Temperature Logger
version: "2.3.0"
email: till.korten@tu-dresden.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raspi-templog" # the base hostname & protocol for your site
destination: "/var/www/html/"
include: [".htaccess"]
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
