on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  pi-gen-templog:
    runs-on: ubuntu-latest
    steps:
      # Create a stage 'pitemplog' instructing to add Nodesource repo and install nodejs as dependency

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: raspi-templog
          stage-list: stage0 stage1 stage2
          pi-gen-repository: thawn/pi-gen
          password: 'raspberry'
          hostname: pitemplog
          pi-gen-release: pitemplog
          pi-gen-dir: pi-gen
          timezone: Europe/Berlin
          compression: gz
          compression-level: 6
          username: pi
          disable-first-boot-user-rename: 1
          export-last-stage-only: true
          verbose-output: true

      - uses: actions/upload-artifact@v4
        with:
          name: pitemplog-image
          path: ${{ steps.build.outputs.image-path }}